[2021-10-14T09:55:58.285692+00:00] php.DEBUG: User Warning: Configure the "curl.cainfo", "openssl.cafile" or "openssl.capath" php.ini setting to enable the CurlHttpClient {"exception":{"Symfony\\Component\\ErrorHandler\\Exception\\SilencedErrorContext":{"severity":512,"file":"C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\symfony\\http-client\\HttpClient.php","line":57,"trace":[{"file":"C:\\MAMP\\htdocs\\P6_01_projet\\var\\cache\\dev\\ContainerReWqdGy\\App_KernelDevDebugContainer.php","line":1084,"function":"create","class":"Symfony\\Component\\HttpClient\\HttpClient","type":"::"}],"count":1}}} []
[2021-10-14T09:55:58.286123+00:00] php.DEBUG: User Notice: Upgrade the curl extension or run "composer require amphp/http-client" to perform async HTTP operations, including full HTTP/2 support {"exception":{"Symfony\\Component\\ErrorHandler\\Exception\\SilencedErrorContext":{"severity":1024,"file":"C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\symfony\\http-client\\HttpClient.php","line":64,"trace":[{"file":"C:\\MAMP\\htdocs\\P6_01_projet\\var\\cache\\dev\\ContainerReWqdGy\\App_KernelDevDebugContainer.php","line":1084,"function":"create","class":"Symfony\\Component\\HttpClient\\HttpClient","type":"::"}],"count":1}}} []
[2021-10-14T09:55:58.299178+00:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET http://127.0.0.1/P6_01_projet/public/" (from "http://127.0.0.1/P6_01_projet/")" at C:\MAMP\htdocs\P6_01_projet\vendor\symfony\http-kernel\EventListener\RouterListener.php line 136 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET http://127.0.0.1/P6_01_projet/public/\" (from \"http://127.0.0.1/P6_01_projet/\") at C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\symfony\\http-kernel\\EventListener\\RouterListener.php:136)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\NoConfigurationException(code: 0):  at C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\symfony\\routing\\Matcher\\Dumper\\CompiledUrlMatcherTrait.php:182)"} []
[2021-10-14T11:43:08.980314+00:00] php.DEBUG: User Warning: Configure the "curl.cainfo", "openssl.cafile" or "openssl.capath" php.ini setting to enable the CurlHttpClient {"exception":{"Symfony\\Component\\ErrorHandler\\Exception\\SilencedErrorContext":{"severity":512,"file":"C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\symfony\\http-client\\HttpClient.php","line":57,"trace":[{"file":"C:\\MAMP\\htdocs\\P6_01_projet\\var\\cache\\dev\\ContainerReWqdGy\\App_KernelDevDebugContainer.php","line":1084,"function":"create","class":"Symfony\\Component\\HttpClient\\HttpClient","type":"::"}],"count":1}}} []
[2021-10-14T11:43:08.985188+00:00] php.DEBUG: User Notice: Upgrade the curl extension or run "composer require amphp/http-client" to perform async HTTP operations, including full HTTP/2 support {"exception":{"Symfony\\Component\\ErrorHandler\\Exception\\SilencedErrorContext":{"severity":1024,"file":"C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\symfony\\http-client\\HttpClient.php","line":64,"trace":[{"file":"C:\\MAMP\\htdocs\\P6_01_projet\\var\\cache\\dev\\ContainerReWqdGy\\App_KernelDevDebugContainer.php","line":1084,"function":"create","class":"Symfony\\Component\\HttpClient\\HttpClient","type":"::"}],"count":1}}} []
[2021-10-14T11:43:09.060623+00:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET http://127.0.0.1/P6_01_projet/public/"" at C:\MAMP\htdocs\P6_01_projet\vendor\symfony\http-kernel\EventListener\RouterListener.php line 136 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET http://127.0.0.1/P6_01_projet/public/\" at C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\symfony\\http-kernel\\EventListener\\RouterListener.php:136)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\NoConfigurationException(code: 0):  at C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\symfony\\routing\\Matcher\\Dumper\\CompiledUrlMatcherTrait.php:182)"} []
[2021-10-14T12:26:39.512429+00:00] request.INFO: Matched route "question_homepage". {"route":"question_homepage","route_parameters":{"_route":"question_homepage","_controller":"QuestionController::homepage"},"request_uri":"http://127.0.0.1/P6_01_projet/public/","method":"GET"} []
[2021-10-14T12:26:39.522453+00:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":0} []
[2021-10-14T12:26:39.529785+00:00] php.DEBUG: User Warning: Configure the "curl.cainfo", "openssl.cafile" or "openssl.capath" php.ini setting to enable the CurlHttpClient {"exception":{"Symfony\\Component\\ErrorHandler\\Exception\\SilencedErrorContext":{"severity":512,"file":"C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\symfony\\http-client\\HttpClient.php","line":57,"trace":[{"file":"C:\\MAMP\\htdocs\\P6_01_projet\\var\\cache\\dev\\ContainerMZWWShC\\App_KernelDevDebugContainer.php","line":1084,"function":"create","class":"Symfony\\Component\\HttpClient\\HttpClient","type":"::"}],"count":1}}} []
[2021-10-14T12:26:39.529999+00:00] php.DEBUG: User Notice: Upgrade the curl extension or run "composer require amphp/http-client" to perform async HTTP operations, including full HTTP/2 support {"exception":{"Symfony\\Component\\ErrorHandler\\Exception\\SilencedErrorContext":{"severity":1024,"file":"C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\symfony\\http-client\\HttpClient.php","line":64,"trace":[{"file":"C:\\MAMP\\htdocs\\P6_01_projet\\var\\cache\\dev\\ContainerMZWWShC\\App_KernelDevDebugContainer.php","line":1084,"function":"create","class":"Symfony\\Component\\HttpClient\\HttpClient","type":"::"}],"count":1}}} []
[2021-10-14T12:26:39.563756+00:00] request.CRITICAL: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\ControllerDoesNotReturnResponseException: "The controller must return a "Symfony\Component\HttpFoundation\Response" object but it returned null. Did you forget to add a return statement somewhere in your controller?" at C:\MAMP\htdocs\P6_01_projet\src\Controller\homeController.php line 13 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\ControllerDoesNotReturnResponseException(code: 0): The controller must return a \"Symfony\\Component\\HttpFoundation\\Response\" object but it returned null. Did you forget to add a return statement somewhere in your controller? at C:\\MAMP\\htdocs\\P6_01_projet\\src\\Controller\\homeController.php:13)"} []
[2021-10-14T12:26:39.763543+00:00] request.CRITICAL: Exception thrown when handling an exception (Doctrine\DBAL\Exception\DriverException: An exception occurred in driver: could not find driver at C:\MAMP\htdocs\P6_01_projet\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\AbstractPostgreSQLDriver.php line 102) {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in driver: could not find driver at C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractPostgreSQLDriver.php:102)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDO\\Exception.php:18)\n[previous exception] [object] (PDOException(code: 0): could not find driver at C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOConnection.php:40)"} []
[2021-10-14T12:26:39.764906+00:00] php.CRITICAL: Uncaught Exception: An exception occurred in driver: could not find driver {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in driver: could not find driver at C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractPostgreSQLDriver.php:102)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDO\\Exception.php:18)\n[previous exception] [object] (PDOException(code: 0): could not find driver at C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOConnection.php:40)\n[previous exception] [object] (Symfony\\Component\\HttpKernel\\Exception\\ControllerDoesNotReturnResponseException(code: 0): The controller must return a \"Symfony\\Component\\HttpFoundation\\Response\" object but it returned null. Did you forget to add a return statement somewhere in your controller? at C:\\MAMP\\htdocs\\P6_01_projet\\src\\Controller\\homeController.php:13)"} []
[2021-10-14T12:26:39.770007+00:00] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\DriverException: "An exception occurred in driver: could not find driver" at C:\MAMP\htdocs\P6_01_projet\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\AbstractPostgreSQLDriver.php line 102 {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in driver: could not find driver at C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractPostgreSQLDriver.php:102)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDO\\Exception.php:18)\n[previous exception] [object] (PDOException(code: 0): could not find driver at C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOConnection.php:40)\n[previous exception] [object] (Symfony\\Component\\HttpKernel\\Exception\\ControllerDoesNotReturnResponseException(code: 0): The controller must return a \"Symfony\\Component\\HttpFoundation\\Response\" object but it returned null. Did you forget to add a return statement somewhere in your controller? at C:\\MAMP\\htdocs\\P6_01_projet\\src\\Controller\\homeController.php:13)"} []
[2021-10-14T12:26:40.482884+00:00] request.CRITICAL: Exception thrown when handling an exception (Doctrine\DBAL\Exception\DriverException: An exception occurred in driver: could not find driver at C:\MAMP\htdocs\P6_01_projet\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\AbstractPostgreSQLDriver.php line 102) {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in driver: could not find driver at C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractPostgreSQLDriver.php:102)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDO\\Exception.php:18)\n[previous exception] [object] (PDOException(code: 0): could not find driver at C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOConnection.php:40)"} []
[2021-10-14T12:26:40.483276+00:00] php.CRITICAL: Uncaught Exception: An exception occurred in driver: could not find driver {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in driver: could not find driver at C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractPostgreSQLDriver.php:102)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDO\\Exception.php:18)\n[previous exception] [object] (PDOException(code: 0): could not find driver at C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOConnection.php:40)\n[previous exception] [object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in driver: could not find driver at C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractPostgreSQLDriver.php:102)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDO\\Exception.php:18)\n[previous exception] [object] (PDOException(code: 0): could not find driver at C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOConnection.php:40)\n[previous exception] [object] (Symfony\\Component\\HttpKernel\\Exception\\ControllerDoesNotReturnResponseException(code: 0): The controller must return a \"Symfony\\Component\\HttpFoundation\\Response\" object but it returned null. Did you forget to add a return statement somewhere in your controller? at C:\\MAMP\\htdocs\\P6_01_projet\\src\\Controller\\homeController.php:13)"} []
[2021-10-14T12:27:08.226813+00:00] php.DEBUG: User Warning: Configure the "curl.cainfo", "openssl.cafile" or "openssl.capath" php.ini setting to enable the CurlHttpClient {"exception":{"Symfony\\Component\\ErrorHandler\\Exception\\SilencedErrorContext":{"severity":512,"file":"C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\symfony\\http-client\\HttpClient.php","line":57,"trace":[{"file":"C:\\MAMP\\htdocs\\P6_01_projet\\var\\cache\\dev\\ContainerMZWWShC\\App_KernelDevDebugContainer.php","line":1084,"function":"create","class":"Symfony\\Component\\HttpClient\\HttpClient","type":"::"}],"count":1}}} []
[2021-10-14T12:27:08.231146+00:00] php.DEBUG: User Notice: Upgrade the curl extension or run "composer require amphp/http-client" to perform async HTTP operations, including full HTTP/2 support {"exception":{"Symfony\\Component\\ErrorHandler\\Exception\\SilencedErrorContext":{"severity":1024,"file":"C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\symfony\\http-client\\HttpClient.php","line":64,"trace":[{"file":"C:\\MAMP\\htdocs\\P6_01_projet\\var\\cache\\dev\\ContainerMZWWShC\\App_KernelDevDebugContainer.php","line":1084,"function":"create","class":"Symfony\\Component\\HttpClient\\HttpClient","type":"::"}],"count":1}}} []
[2021-10-14T12:27:08.293094+00:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET http://127.0.0.1/P6_01_projet/public/"" at C:\MAMP\htdocs\P6_01_projet\vendor\symfony\http-kernel\EventListener\RouterListener.php line 136 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET http://127.0.0.1/P6_01_projet/public/\" at C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\symfony\\http-kernel\\EventListener\\RouterListener.php:136)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\NoConfigurationException(code: 0):  at C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\symfony\\routing\\Matcher\\Dumper\\CompiledUrlMatcherTrait.php:182)"} []
[2021-10-14T12:29:46.846100+00:00] request.INFO: Matched route "question_homepage". {"route":"question_homepage","route_parameters":{"_route":"question_homepage","_controller":"QuestionController::homepage"},"request_uri":"http://127.0.0.1/P6_01_projet/public/","method":"GET"} []
[2021-10-14T12:29:46.856829+00:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":0} []
[2021-10-14T12:29:46.858838+00:00] php.CRITICAL: Uncaught Error: Class 'Response' not found {"exception":"[object] (Error(code: 0): Class 'Response' not found at C:\\MAMP\\htdocs\\P6_01_projet\\src\\Controller\\homeController.php:11)"} []
[2021-10-14T12:29:48.229587+00:00] php.DEBUG: User Warning: Configure the "curl.cainfo", "openssl.cafile" or "openssl.capath" php.ini setting to enable the CurlHttpClient {"exception":{"Symfony\\Component\\ErrorHandler\\Exception\\SilencedErrorContext":{"severity":512,"file":"C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\symfony\\http-client\\HttpClient.php","line":57,"trace":[{"file":"C:\\MAMP\\htdocs\\P6_01_projet\\var\\cache\\dev\\ContainerMZWWShC\\App_KernelDevDebugContainer.php","line":1084,"function":"create","class":"Symfony\\Component\\HttpClient\\HttpClient","type":"::"}],"count":1}}} []
[2021-10-14T12:29:48.229683+00:00] php.DEBUG: User Notice: Upgrade the curl extension or run "composer require amphp/http-client" to perform async HTTP operations, including full HTTP/2 support {"exception":{"Symfony\\Component\\ErrorHandler\\Exception\\SilencedErrorContext":{"severity":1024,"file":"C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\symfony\\http-client\\HttpClient.php","line":64,"trace":[{"file":"C:\\MAMP\\htdocs\\P6_01_projet\\var\\cache\\dev\\ContainerMZWWShC\\App_KernelDevDebugContainer.php","line":1084,"function":"create","class":"Symfony\\Component\\HttpClient\\HttpClient","type":"::"}],"count":1}}} []
[2021-10-14T12:29:48.249340+00:00] request.CRITICAL: Uncaught PHP Exception Symfony\Component\ErrorHandler\Error\ClassNotFoundError: "Attempted to load class "Response" from the global namespace. Did you forget a "use" statement for e.g. "Symfony\Flex\Response", "Symfony\Component\HttpFoundation\Response" or "Symfony\Component\BrowserKit\Response"?" at C:\MAMP\htdocs\P6_01_projet\src\Controller\homeController.php line 11 {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\ClassNotFoundError(code: 0): Attempted to load class \"Response\" from the global namespace.\nDid you forget a \"use\" statement for e.g. \"Symfony\\Flex\\Response\", \"Symfony\\Component\\HttpFoundation\\Response\" or \"Symfony\\Component\\BrowserKit\\Response\"? at C:\\MAMP\\htdocs\\P6_01_projet\\src\\Controller\\homeController.php:11)"} []
[2021-10-14T12:29:48.369884+00:00] request.CRITICAL: Exception thrown when handling an exception (Doctrine\DBAL\Exception\DriverException: An exception occurred in driver: could not find driver at C:\MAMP\htdocs\P6_01_projet\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\AbstractPostgreSQLDriver.php line 102) {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in driver: could not find driver at C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractPostgreSQLDriver.php:102)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDO\\Exception.php:18)\n[previous exception] [object] (PDOException(code: 0): could not find driver at C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOConnection.php:40)"} []
[2021-10-14T12:29:48.370040+00:00] php.CRITICAL: Uncaught Exception: An exception occurred in driver: could not find driver {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in driver: could not find driver at C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractPostgreSQLDriver.php:102)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDO\\Exception.php:18)\n[previous exception] [object] (PDOException(code: 0): could not find driver at C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOConnection.php:40)\n[previous exception] [object] (Symfony\\Component\\ErrorHandler\\Error\\ClassNotFoundError(code: 0): Attempted to load class \"Response\" from the global namespace.\nDid you forget a \"use\" statement for e.g. \"Symfony\\Flex\\Response\", \"Symfony\\Component\\HttpFoundation\\Response\" or \"Symfony\\Component\\BrowserKit\\Response\"? at C:\\MAMP\\htdocs\\P6_01_projet\\src\\Controller\\homeController.php:11)"} []
[2021-10-14T12:30:23.334978+00:00] request.INFO: Matched route "home_homepage". {"route":"home_homepage","route_parameters":{"_route":"home_homepage","_controller":"homeController::homepage"},"request_uri":"http://127.0.0.1/P6_01_projet/public/","method":"GET"} []
[2021-10-14T12:30:23.346054+00:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":0} []
[2021-10-14T12:30:23.347910+00:00] php.CRITICAL: Uncaught Error: Class 'Response' not found {"exception":"[object] (Error(code: 0): Class 'Response' not found at C:\\MAMP\\htdocs\\P6_01_projet\\src\\Controller\\homeController.php:11)"} []
[2021-10-14T12:30:24.652414+00:00] php.DEBUG: User Warning: Configure the "curl.cainfo", "openssl.cafile" or "openssl.capath" php.ini setting to enable the CurlHttpClient {"exception":{"Symfony\\Component\\ErrorHandler\\Exception\\SilencedErrorContext":{"severity":512,"file":"C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\symfony\\http-client\\HttpClient.php","line":57,"trace":[{"file":"C:\\MAMP\\htdocs\\P6_01_projet\\var\\cache\\dev\\ContainerMZWWShC\\App_KernelDevDebugContainer.php","line":1084,"function":"create","class":"Symfony\\Component\\HttpClient\\HttpClient","type":"::"}],"count":1}}} []
[2021-10-14T12:30:24.652552+00:00] php.DEBUG: User Notice: Upgrade the curl extension or run "composer require amphp/http-client" to perform async HTTP operations, including full HTTP/2 support {"exception":{"Symfony\\Component\\ErrorHandler\\Exception\\SilencedErrorContext":{"severity":1024,"file":"C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\symfony\\http-client\\HttpClient.php","line":64,"trace":[{"file":"C:\\MAMP\\htdocs\\P6_01_projet\\var\\cache\\dev\\ContainerMZWWShC\\App_KernelDevDebugContainer.php","line":1084,"function":"create","class":"Symfony\\Component\\HttpClient\\HttpClient","type":"::"}],"count":1}}} []
[2021-10-14T12:30:24.672224+00:00] request.CRITICAL: Uncaught PHP Exception Symfony\Component\ErrorHandler\Error\ClassNotFoundError: "Attempted to load class "Response" from the global namespace. Did you forget a "use" statement for e.g. "Symfony\Flex\Response", "Symfony\Component\HttpFoundation\Response" or "Symfony\Component\BrowserKit\Response"?" at C:\MAMP\htdocs\P6_01_projet\src\Controller\homeController.php line 11 {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\ClassNotFoundError(code: 0): Attempted to load class \"Response\" from the global namespace.\nDid you forget a \"use\" statement for e.g. \"Symfony\\Flex\\Response\", \"Symfony\\Component\\HttpFoundation\\Response\" or \"Symfony\\Component\\BrowserKit\\Response\"? at C:\\MAMP\\htdocs\\P6_01_projet\\src\\Controller\\homeController.php:11)"} []
[2021-10-14T12:30:24.798733+00:00] request.CRITICAL: Exception thrown when handling an exception (Doctrine\DBAL\Exception\DriverException: An exception occurred in driver: could not find driver at C:\MAMP\htdocs\P6_01_projet\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\AbstractPostgreSQLDriver.php line 102) {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in driver: could not find driver at C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractPostgreSQLDriver.php:102)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDO\\Exception.php:18)\n[previous exception] [object] (PDOException(code: 0): could not find driver at C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOConnection.php:40)"} []
[2021-10-14T12:30:24.798889+00:00] php.CRITICAL: Uncaught Exception: An exception occurred in driver: could not find driver {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in driver: could not find driver at C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractPostgreSQLDriver.php:102)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDO\\Exception.php:18)\n[previous exception] [object] (PDOException(code: 0): could not find driver at C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOConnection.php:40)\n[previous exception] [object] (Symfony\\Component\\ErrorHandler\\Error\\ClassNotFoundError(code: 0): Attempted to load class \"Response\" from the global namespace.\nDid you forget a \"use\" statement for e.g. \"Symfony\\Flex\\Response\", \"Symfony\\Component\\HttpFoundation\\Response\" or \"Symfony\\Component\\BrowserKit\\Response\"? at C:\\MAMP\\htdocs\\P6_01_projet\\src\\Controller\\homeController.php:11)"} []
[2021-10-14T12:32:29.887599+00:00] request.INFO: Matched route "app_home_homepage". {"route":"app_home_homepage","route_parameters":{"_route":"app_home_homepage","_controller":"App\\Controller\\homeController::homepage"},"request_uri":"http://127.0.0.1/P6_01_projet/public/","method":"GET"} []
[2021-10-14T12:32:29.891500+00:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":0} []
[2021-10-14T12:32:29.893874+00:00] php.DEBUG: User Warning: Configure the "curl.cainfo", "openssl.cafile" or "openssl.capath" php.ini setting to enable the CurlHttpClient {"exception":{"Symfony\\Component\\ErrorHandler\\Exception\\SilencedErrorContext":{"severity":512,"file":"C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\symfony\\http-client\\HttpClient.php","line":57,"trace":[{"file":"C:\\MAMP\\htdocs\\P6_01_projet\\var\\cache\\dev\\ContainerMZWWShC\\App_KernelDevDebugContainer.php","line":1084,"function":"create","class":"Symfony\\Component\\HttpClient\\HttpClient","type":"::"}],"count":1}}} []
[2021-10-14T12:32:29.893954+00:00] php.DEBUG: User Notice: Upgrade the curl extension or run "composer require amphp/http-client" to perform async HTTP operations, including full HTTP/2 support {"exception":{"Symfony\\Component\\ErrorHandler\\Exception\\SilencedErrorContext":{"severity":1024,"file":"C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\symfony\\http-client\\HttpClient.php","line":64,"trace":[{"file":"C:\\MAMP\\htdocs\\P6_01_projet\\var\\cache\\dev\\ContainerMZWWShC\\App_KernelDevDebugContainer.php","line":1084,"function":"create","class":"Symfony\\Component\\HttpClient\\HttpClient","type":"::"}],"count":1}}} []
[2021-10-14T12:32:29.934793+00:00] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\DriverException: "An exception occurred in driver: could not find driver" at C:\MAMP\htdocs\P6_01_projet\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\AbstractPostgreSQLDriver.php line 102 {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in driver: could not find driver at C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractPostgreSQLDriver.php:102)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDO\\Exception.php:18)\n[previous exception] [object] (PDOException(code: 0): could not find driver at C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOConnection.php:40)"} []
[2021-10-14T12:32:30.186953+00:00] request.CRITICAL: Exception thrown when handling an exception (Doctrine\DBAL\Exception\DriverException: An exception occurred in driver: could not find driver at C:\MAMP\htdocs\P6_01_projet\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\AbstractPostgreSQLDriver.php line 102) {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in driver: could not find driver at C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractPostgreSQLDriver.php:102)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDO\\Exception.php:18)\n[previous exception] [object] (PDOException(code: 0): could not find driver at C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOConnection.php:40)"} []
[2021-10-14T12:32:30.187580+00:00] php.CRITICAL: Uncaught Exception: An exception occurred in driver: could not find driver {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in driver: could not find driver at C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractPostgreSQLDriver.php:102)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDO\\Exception.php:18)\n[previous exception] [object] (PDOException(code: 0): could not find driver at C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOConnection.php:40)\n[previous exception] [object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in driver: could not find driver at C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractPostgreSQLDriver.php:102)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDO\\Exception.php:18)\n[previous exception] [object] (PDOException(code: 0): could not find driver at C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOConnection.php:40)"} []
[2021-10-14T12:32:30.189540+00:00] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\DriverException: "An exception occurred in driver: could not find driver" at C:\MAMP\htdocs\P6_01_projet\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\AbstractPostgreSQLDriver.php line 102 {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in driver: could not find driver at C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractPostgreSQLDriver.php:102)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDO\\Exception.php:18)\n[previous exception] [object] (PDOException(code: 0): could not find driver at C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOConnection.php:40)\n[previous exception] [object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in driver: could not find driver at C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractPostgreSQLDriver.php:102)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDO\\Exception.php:18)\n[previous exception] [object] (PDOException(code: 0): could not find driver at C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOConnection.php:40)"} []
[2021-10-14T12:32:30.674589+00:00] request.CRITICAL: Exception thrown when handling an exception (Doctrine\DBAL\Exception\DriverException: An exception occurred in driver: could not find driver at C:\MAMP\htdocs\P6_01_projet\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\AbstractPostgreSQLDriver.php line 102) {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in driver: could not find driver at C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractPostgreSQLDriver.php:102)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDO\\Exception.php:18)\n[previous exception] [object] (PDOException(code: 0): could not find driver at C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOConnection.php:40)"} []
[2021-10-14T12:32:30.674803+00:00] php.CRITICAL: Uncaught Exception: An exception occurred in driver: could not find driver {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in driver: could not find driver at C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractPostgreSQLDriver.php:102)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDO\\Exception.php:18)\n[previous exception] [object] (PDOException(code: 0): could not find driver at C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOConnection.php:40)\n[previous exception] [object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in driver: could not find driver at C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractPostgreSQLDriver.php:102)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDO\\Exception.php:18)\n[previous exception] [object] (PDOException(code: 0): could not find driver at C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOConnection.php:40)\n[previous exception] [object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in driver: could not find driver at C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractPostgreSQLDriver.php:102)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDO\\Exception.php:18)\n[previous exception] [object] (PDOException(code: 0): could not find driver at C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOConnection.php:40)"} []
[2021-10-14T12:39:03.383134+00:00] request.INFO: Matched route "app_home_homepage". {"route":"app_home_homepage","route_parameters":{"_route":"app_home_homepage","_controller":"App\\Controller\\homeController::homepage"},"request_uri":"http://127.0.0.1/P6_01_projet/public/","method":"GET"} []
[2021-10-14T12:39:03.396179+00:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":0} []
[2021-10-14T12:39:03.401039+00:00] php.DEBUG: User Warning: Configure the "curl.cainfo", "openssl.cafile" or "openssl.capath" php.ini setting to enable the CurlHttpClient {"exception":{"Symfony\\Component\\ErrorHandler\\Exception\\SilencedErrorContext":{"severity":512,"file":"C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\symfony\\http-client\\HttpClient.php","line":57,"trace":[{"file":"C:\\MAMP\\htdocs\\P6_01_projet\\var\\cache\\dev\\ContainerMZWWShC\\App_KernelDevDebugContainer.php","line":1084,"function":"create","class":"Symfony\\Component\\HttpClient\\HttpClient","type":"::"}],"count":1}}} []
[2021-10-14T12:39:03.401122+00:00] php.DEBUG: User Notice: Upgrade the curl extension or run "composer require amphp/http-client" to perform async HTTP operations, including full HTTP/2 support {"exception":{"Symfony\\Component\\ErrorHandler\\Exception\\SilencedErrorContext":{"severity":1024,"file":"C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\symfony\\http-client\\HttpClient.php","line":64,"trace":[{"file":"C:\\MAMP\\htdocs\\P6_01_projet\\var\\cache\\dev\\ContainerMZWWShC\\App_KernelDevDebugContainer.php","line":1084,"function":"create","class":"Symfony\\Component\\HttpClient\\HttpClient","type":"::"}],"count":1}}} []
[2021-10-14T12:39:03.488474+00:00] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\DriverException: "An exception occurred in driver: could not find driver" at C:\MAMP\htdocs\P6_01_projet\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\AbstractPostgreSQLDriver.php line 102 {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in driver: could not find driver at C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractPostgreSQLDriver.php:102)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDO\\Exception.php:18)\n[previous exception] [object] (PDOException(code: 0): could not find driver at C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOConnection.php:40)"} []
[2021-10-14T12:39:03.783173+00:00] request.CRITICAL: Exception thrown when handling an exception (Doctrine\DBAL\Exception\DriverException: An exception occurred in driver: could not find driver at C:\MAMP\htdocs\P6_01_projet\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\AbstractPostgreSQLDriver.php line 102) {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in driver: could not find driver at C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractPostgreSQLDriver.php:102)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDO\\Exception.php:18)\n[previous exception] [object] (PDOException(code: 0): could not find driver at C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOConnection.php:40)"} []
[2021-10-14T12:39:03.783743+00:00] php.CRITICAL: Uncaught Exception: An exception occurred in driver: could not find driver {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in driver: could not find driver at C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractPostgreSQLDriver.php:102)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDO\\Exception.php:18)\n[previous exception] [object] (PDOException(code: 0): could not find driver at C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOConnection.php:40)\n[previous exception] [object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in driver: could not find driver at C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractPostgreSQLDriver.php:102)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDO\\Exception.php:18)\n[previous exception] [object] (PDOException(code: 0): could not find driver at C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOConnection.php:40)"} []
[2021-10-14T12:39:03.785639+00:00] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\DriverException: "An exception occurred in driver: could not find driver" at C:\MAMP\htdocs\P6_01_projet\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\AbstractPostgreSQLDriver.php line 102 {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in driver: could not find driver at C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractPostgreSQLDriver.php:102)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDO\\Exception.php:18)\n[previous exception] [object] (PDOException(code: 0): could not find driver at C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOConnection.php:40)\n[previous exception] [object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in driver: could not find driver at C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractPostgreSQLDriver.php:102)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDO\\Exception.php:18)\n[previous exception] [object] (PDOException(code: 0): could not find driver at C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOConnection.php:40)"} []
[2021-10-14T12:39:04.273859+00:00] request.CRITICAL: Exception thrown when handling an exception (Doctrine\DBAL\Exception\DriverException: An exception occurred in driver: could not find driver at C:\MAMP\htdocs\P6_01_projet\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\AbstractPostgreSQLDriver.php line 102) {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in driver: could not find driver at C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractPostgreSQLDriver.php:102)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDO\\Exception.php:18)\n[previous exception] [object] (PDOException(code: 0): could not find driver at C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOConnection.php:40)"} []
[2021-10-14T12:39:04.274070+00:00] php.CRITICAL: Uncaught Exception: An exception occurred in driver: could not find driver {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in driver: could not find driver at C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractPostgreSQLDriver.php:102)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDO\\Exception.php:18)\n[previous exception] [object] (PDOException(code: 0): could not find driver at C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOConnection.php:40)\n[previous exception] [object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in driver: could not find driver at C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractPostgreSQLDriver.php:102)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDO\\Exception.php:18)\n[previous exception] [object] (PDOException(code: 0): could not find driver at C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOConnection.php:40)\n[previous exception] [object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in driver: could not find driver at C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractPostgreSQLDriver.php:102)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDO\\Exception.php:18)\n[previous exception] [object] (PDOException(code: 0): could not find driver at C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOConnection.php:40)"} []
[2021-10-14T12:41:05.393968+00:00] request.INFO: Matched route "app_home_homepage". {"route":"app_home_homepage","route_parameters":{"_route":"app_home_homepage","_controller":"App\\Controller\\homeController::homepage"},"request_uri":"http://127.0.0.1/P6_01_projet/public/","method":"GET"} []
[2021-10-14T12:41:05.405513+00:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":0} []
[2021-10-14T12:41:05.418955+00:00] php.DEBUG: User Warning: Configure the "curl.cainfo", "openssl.cafile" or "openssl.capath" php.ini setting to enable the CurlHttpClient {"exception":{"Symfony\\Component\\ErrorHandler\\Exception\\SilencedErrorContext":{"severity":512,"file":"C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\symfony\\http-client\\HttpClient.php","line":57,"trace":[{"file":"C:\\MAMP\\htdocs\\P6_01_projet\\var\\cache\\dev\\ContainerMZWWShC\\App_KernelDevDebugContainer.php","line":1084,"function":"create","class":"Symfony\\Component\\HttpClient\\HttpClient","type":"::"}],"count":1}}} []
[2021-10-14T12:41:05.419043+00:00] php.DEBUG: User Notice: Upgrade the curl extension or run "composer require amphp/http-client" to perform async HTTP operations, including full HTTP/2 support {"exception":{"Symfony\\Component\\ErrorHandler\\Exception\\SilencedErrorContext":{"severity":1024,"file":"C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\symfony\\http-client\\HttpClient.php","line":64,"trace":[{"file":"C:\\MAMP\\htdocs\\P6_01_projet\\var\\cache\\dev\\ContainerMZWWShC\\App_KernelDevDebugContainer.php","line":1084,"function":"create","class":"Symfony\\Component\\HttpClient\\HttpClient","type":"::"}],"count":1}}} []
[2021-10-14T12:41:05.498043+00:00] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\DriverException: "An exception occurred in driver: could not find driver" at C:\MAMP\htdocs\P6_01_projet\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\AbstractPostgreSQLDriver.php line 102 {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in driver: could not find driver at C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractPostgreSQLDriver.php:102)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDO\\Exception.php:18)\n[previous exception] [object] (PDOException(code: 0): could not find driver at C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOConnection.php:40)"} []
[2021-10-14T12:41:05.764150+00:00] request.CRITICAL: Exception thrown when handling an exception (Doctrine\DBAL\Exception\DriverException: An exception occurred in driver: could not find driver at C:\MAMP\htdocs\P6_01_projet\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\AbstractPostgreSQLDriver.php line 102) {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in driver: could not find driver at C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractPostgreSQLDriver.php:102)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDO\\Exception.php:18)\n[previous exception] [object] (PDOException(code: 0): could not find driver at C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOConnection.php:40)"} []
[2021-10-14T12:41:05.764608+00:00] php.CRITICAL: Uncaught Exception: An exception occurred in driver: could not find driver {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in driver: could not find driver at C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractPostgreSQLDriver.php:102)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDO\\Exception.php:18)\n[previous exception] [object] (PDOException(code: 0): could not find driver at C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOConnection.php:40)\n[previous exception] [object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in driver: could not find driver at C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractPostgreSQLDriver.php:102)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDO\\Exception.php:18)\n[previous exception] [object] (PDOException(code: 0): could not find driver at C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOConnection.php:40)"} []
[2021-10-14T12:41:05.766467+00:00] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\DriverException: "An exception occurred in driver: could not find driver" at C:\MAMP\htdocs\P6_01_projet\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\AbstractPostgreSQLDriver.php line 102 {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in driver: could not find driver at C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractPostgreSQLDriver.php:102)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDO\\Exception.php:18)\n[previous exception] [object] (PDOException(code: 0): could not find driver at C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOConnection.php:40)\n[previous exception] [object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in driver: could not find driver at C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractPostgreSQLDriver.php:102)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDO\\Exception.php:18)\n[previous exception] [object] (PDOException(code: 0): could not find driver at C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOConnection.php:40)"} []
[2021-10-14T12:41:06.243719+00:00] request.CRITICAL: Exception thrown when handling an exception (Doctrine\DBAL\Exception\DriverException: An exception occurred in driver: could not find driver at C:\MAMP\htdocs\P6_01_projet\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\AbstractPostgreSQLDriver.php line 102) {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in driver: could not find driver at C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractPostgreSQLDriver.php:102)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDO\\Exception.php:18)\n[previous exception] [object] (PDOException(code: 0): could not find driver at C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOConnection.php:40)"} []
[2021-10-14T12:41:06.243905+00:00] php.CRITICAL: Uncaught Exception: An exception occurred in driver: could not find driver {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in driver: could not find driver at C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractPostgreSQLDriver.php:102)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDO\\Exception.php:18)\n[previous exception] [object] (PDOException(code: 0): could not find driver at C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOConnection.php:40)\n[previous exception] [object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in driver: could not find driver at C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractPostgreSQLDriver.php:102)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDO\\Exception.php:18)\n[previous exception] [object] (PDOException(code: 0): could not find driver at C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOConnection.php:40)\n[previous exception] [object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in driver: could not find driver at C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractPostgreSQLDriver.php:102)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDO\\Exception.php:18)\n[previous exception] [object] (PDOException(code: 0): could not find driver at C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOConnection.php:40)"} []
[2021-10-14T12:46:27.041027+00:00] request.INFO: Matched route "app_home_homepage". {"route":"app_home_homepage","route_parameters":{"_route":"app_home_homepage","_controller":"App\\Controller\\homeController::homepage"},"request_uri":"http://127.0.0.1/P6_01_projet/public/","method":"GET"} []
[2021-10-14T12:46:27.052075+00:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":0} []
[2021-10-14T12:46:27.064241+00:00] php.DEBUG: User Warning: Configure the "curl.cainfo", "openssl.cafile" or "openssl.capath" php.ini setting to enable the CurlHttpClient {"exception":{"Symfony\\Component\\ErrorHandler\\Exception\\SilencedErrorContext":{"severity":512,"file":"C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\symfony\\http-client\\HttpClient.php","line":57,"trace":[{"file":"C:\\MAMP\\htdocs\\P6_01_projet\\var\\cache\\dev\\ContainerMZWWShC\\App_KernelDevDebugContainer.php","line":1084,"function":"create","class":"Symfony\\Component\\HttpClient\\HttpClient","type":"::"}],"count":1}}} []
[2021-10-14T12:46:27.064342+00:00] php.DEBUG: User Notice: Upgrade the curl extension or run "composer require amphp/http-client" to perform async HTTP operations, including full HTTP/2 support {"exception":{"Symfony\\Component\\ErrorHandler\\Exception\\SilencedErrorContext":{"severity":1024,"file":"C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\symfony\\http-client\\HttpClient.php","line":64,"trace":[{"file":"C:\\MAMP\\htdocs\\P6_01_projet\\var\\cache\\dev\\ContainerMZWWShC\\App_KernelDevDebugContainer.php","line":1084,"function":"create","class":"Symfony\\Component\\HttpClient\\HttpClient","type":"::"}],"count":1}}} []
[2021-10-14T12:46:27.199690+00:00] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\ConnectionException: "An exception occurred in driver: SQLSTATE[HY000] [1045] Access denied for user 'db_user'@'localhost' (using password: YES)" at C:\MAMP\htdocs\P6_01_projet\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\AbstractMySQLDriver.php line 112 {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occurred in driver: SQLSTATE[HY000] [1045] Access denied for user 'db_user'@'localhost' (using password: YES) at C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractMySQLDriver.php:112)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'db_user'@'localhost' (using password: YES) at C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDO\\Exception.php:18)\n[previous exception] [object] (PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'db_user'@'localhost' (using password: YES) at C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOConnection.php:40)"} []
[2021-10-14T12:46:27.548834+00:00] request.CRITICAL: Exception thrown when handling an exception (Doctrine\DBAL\Exception\ConnectionException: An exception occurred in driver: SQLSTATE[HY000] [1045] Access denied for user 'db_user'@'localhost' (using password: YES) at C:\MAMP\htdocs\P6_01_projet\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\AbstractMySQLDriver.php line 112) {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occurred in driver: SQLSTATE[HY000] [1045] Access denied for user 'db_user'@'localhost' (using password: YES) at C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractMySQLDriver.php:112)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'db_user'@'localhost' (using password: YES) at C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDO\\Exception.php:18)\n[previous exception] [object] (PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'db_user'@'localhost' (using password: YES) at C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOConnection.php:40)"} []
[2021-10-14T12:46:27.550333+00:00] php.CRITICAL: Uncaught Exception: An exception occurred in driver: SQLSTATE[HY000] [1045] Access denied for user 'db_user'@'localhost' (using password: YES) {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occurred in driver: SQLSTATE[HY000] [1045] Access denied for user 'db_user'@'localhost' (using password: YES) at C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractMySQLDriver.php:112)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'db_user'@'localhost' (using password: YES) at C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDO\\Exception.php:18)\n[previous exception] [object] (PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'db_user'@'localhost' (using password: YES) at C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOConnection.php:40)\n[previous exception] [object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occurred in driver: SQLSTATE[HY000] [1045] Access denied for user 'db_user'@'localhost' (using password: YES) at C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractMySQLDriver.php:112)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'db_user'@'localhost' (using password: YES) at C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDO\\Exception.php:18)\n[previous exception] [object] (PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'db_user'@'localhost' (using password: YES) at C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOConnection.php:40)"} []
[2021-10-14T12:46:27.554971+00:00] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\ConnectionException: "An exception occurred in driver: SQLSTATE[HY000] [1045] Access denied for user 'db_user'@'localhost' (using password: YES)" at C:\MAMP\htdocs\P6_01_projet\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\AbstractMySQLDriver.php line 112 {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occurred in driver: SQLSTATE[HY000] [1045] Access denied for user 'db_user'@'localhost' (using password: YES) at C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractMySQLDriver.php:112)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'db_user'@'localhost' (using password: YES) at C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDO\\Exception.php:18)\n[previous exception] [object] (PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'db_user'@'localhost' (using password: YES) at C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOConnection.php:40)\n[previous exception] [object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occurred in driver: SQLSTATE[HY000] [1045] Access denied for user 'db_user'@'localhost' (using password: YES) at C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractMySQLDriver.php:112)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'db_user'@'localhost' (using password: YES) at C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDO\\Exception.php:18)\n[previous exception] [object] (PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'db_user'@'localhost' (using password: YES) at C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOConnection.php:40)"} []
[2021-10-14T12:46:28.129071+00:00] request.CRITICAL: Exception thrown when handling an exception (Doctrine\DBAL\Exception\ConnectionException: An exception occurred in driver: SQLSTATE[HY000] [1045] Access denied for user 'db_user'@'localhost' (using password: YES) at C:\MAMP\htdocs\P6_01_projet\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\AbstractMySQLDriver.php line 112) {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occurred in driver: SQLSTATE[HY000] [1045] Access denied for user 'db_user'@'localhost' (using password: YES) at C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractMySQLDriver.php:112)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'db_user'@'localhost' (using password: YES) at C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDO\\Exception.php:18)\n[previous exception] [object] (PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'db_user'@'localhost' (using password: YES) at C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOConnection.php:40)"} []
[2021-10-14T12:46:28.129481+00:00] php.CRITICAL: Uncaught Exception: An exception occurred in driver: SQLSTATE[HY000] [1045] Access denied for user 'db_user'@'localhost' (using password: YES) {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occurred in driver: SQLSTATE[HY000] [1045] Access denied for user 'db_user'@'localhost' (using password: YES) at C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractMySQLDriver.php:112)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'db_user'@'localhost' (using password: YES) at C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDO\\Exception.php:18)\n[previous exception] [object] (PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'db_user'@'localhost' (using password: YES) at C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOConnection.php:40)\n[previous exception] [object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occurred in driver: SQLSTATE[HY000] [1045] Access denied for user 'db_user'@'localhost' (using password: YES) at C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractMySQLDriver.php:112)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'db_user'@'localhost' (using password: YES) at C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDO\\Exception.php:18)\n[previous exception] [object] (PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'db_user'@'localhost' (using password: YES) at C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOConnection.php:40)\n[previous exception] [object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occurred in driver: SQLSTATE[HY000] [1045] Access denied for user 'db_user'@'localhost' (using password: YES) at C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractMySQLDriver.php:112)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'db_user'@'localhost' (using password: YES) at C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDO\\Exception.php:18)\n[previous exception] [object] (PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'db_user'@'localhost' (using password: YES) at C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOConnection.php:40)"} []
[2021-10-14T12:48:22.494367+00:00] request.INFO: Matched route "app_home_homepage". {"route":"app_home_homepage","route_parameters":{"_route":"app_home_homepage","_controller":"App\\Controller\\homeController::homepage"},"request_uri":"http://127.0.0.1/P6_01_projet/public/","method":"GET"} []
[2021-10-14T12:48:22.503482+00:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":0} []
[2021-10-14T12:48:22.512622+00:00] php.DEBUG: User Warning: Configure the "curl.cainfo", "openssl.cafile" or "openssl.capath" php.ini setting to enable the CurlHttpClient {"exception":{"Symfony\\Component\\ErrorHandler\\Exception\\SilencedErrorContext":{"severity":512,"file":"C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\symfony\\http-client\\HttpClient.php","line":57,"trace":[{"file":"C:\\MAMP\\htdocs\\P6_01_projet\\var\\cache\\dev\\ContainerMZWWShC\\App_KernelDevDebugContainer.php","line":1084,"function":"create","class":"Symfony\\Component\\HttpClient\\HttpClient","type":"::"}],"count":1}}} []
[2021-10-14T12:48:22.512722+00:00] php.DEBUG: User Notice: Upgrade the curl extension or run "composer require amphp/http-client" to perform async HTTP operations, including full HTTP/2 support {"exception":{"Symfony\\Component\\ErrorHandler\\Exception\\SilencedErrorContext":{"severity":1024,"file":"C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\symfony\\http-client\\HttpClient.php","line":64,"trace":[{"file":"C:\\MAMP\\htdocs\\P6_01_projet\\var\\cache\\dev\\ContainerMZWWShC\\App_KernelDevDebugContainer.php","line":1084,"function":"create","class":"Symfony\\Component\\HttpClient\\HttpClient","type":"::"}],"count":1}}} []
[2021-10-14T12:48:22.592708+00:00] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\ConnectionException: "An exception occurred in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: NO)" at C:\MAMP\htdocs\P6_01_projet\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\AbstractMySQLDriver.php line 112 {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occurred in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: NO) at C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractMySQLDriver.php:112)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: NO) at C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDO\\Exception.php:18)\n[previous exception] [object] (PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: NO) at C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOConnection.php:40)"} []
[2021-10-14T12:48:22.898012+00:00] request.CRITICAL: Exception thrown when handling an exception (Doctrine\DBAL\Exception\ConnectionException: An exception occurred in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: NO) at C:\MAMP\htdocs\P6_01_projet\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\AbstractMySQLDriver.php line 112) {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occurred in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: NO) at C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractMySQLDriver.php:112)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: NO) at C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDO\\Exception.php:18)\n[previous exception] [object] (PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: NO) at C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOConnection.php:40)"} []
[2021-10-14T12:48:22.898732+00:00] php.CRITICAL: Uncaught Exception: An exception occurred in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: NO) {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occurred in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: NO) at C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractMySQLDriver.php:112)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: NO) at C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDO\\Exception.php:18)\n[previous exception] [object] (PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: NO) at C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOConnection.php:40)\n[previous exception] [object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occurred in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: NO) at C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractMySQLDriver.php:112)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: NO) at C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDO\\Exception.php:18)\n[previous exception] [object] (PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: NO) at C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOConnection.php:40)"} []
[2021-10-14T12:48:22.901494+00:00] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\ConnectionException: "An exception occurred in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: NO)" at C:\MAMP\htdocs\P6_01_projet\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\AbstractMySQLDriver.php line 112 {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occurred in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: NO) at C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractMySQLDriver.php:112)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: NO) at C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDO\\Exception.php:18)\n[previous exception] [object] (PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: NO) at C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOConnection.php:40)\n[previous exception] [object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occurred in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: NO) at C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractMySQLDriver.php:112)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: NO) at C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDO\\Exception.php:18)\n[previous exception] [object] (PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: NO) at C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOConnection.php:40)"} []
[2021-10-14T12:48:23.478591+00:00] request.CRITICAL: Exception thrown when handling an exception (Doctrine\DBAL\Exception\ConnectionException: An exception occurred in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: NO) at C:\MAMP\htdocs\P6_01_projet\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\AbstractMySQLDriver.php line 112) {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occurred in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: NO) at C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractMySQLDriver.php:112)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: NO) at C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDO\\Exception.php:18)\n[previous exception] [object] (PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: NO) at C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOConnection.php:40)"} []
[2021-10-14T12:48:23.479018+00:00] php.CRITICAL: Uncaught Exception: An exception occurred in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: NO) {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occurred in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: NO) at C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractMySQLDriver.php:112)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: NO) at C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDO\\Exception.php:18)\n[previous exception] [object] (PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: NO) at C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOConnection.php:40)\n[previous exception] [object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occurred in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: NO) at C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractMySQLDriver.php:112)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: NO) at C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDO\\Exception.php:18)\n[previous exception] [object] (PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: NO) at C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOConnection.php:40)\n[previous exception] [object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occurred in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: NO) at C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractMySQLDriver.php:112)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: NO) at C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDO\\Exception.php:18)\n[previous exception] [object] (PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: NO) at C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOConnection.php:40)"} []
[2021-10-14T12:50:01.627717+00:00] request.INFO: Matched route "app_home_homepage". {"route":"app_home_homepage","route_parameters":{"_route":"app_home_homepage","_controller":"App\\Controller\\homeController::homepage"},"request_uri":"http://127.0.0.1/P6_01_projet/public/","method":"GET"} []
[2021-10-14T12:50:01.638778+00:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":0} []
[2021-10-14T12:50:01.653457+00:00] php.DEBUG: User Warning: Configure the "curl.cainfo", "openssl.cafile" or "openssl.capath" php.ini setting to enable the CurlHttpClient {"exception":{"Symfony\\Component\\ErrorHandler\\Exception\\SilencedErrorContext":{"severity":512,"file":"C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\symfony\\http-client\\HttpClient.php","line":57,"trace":[{"file":"C:\\MAMP\\htdocs\\P6_01_projet\\var\\cache\\dev\\ContainerMZWWShC\\App_KernelDevDebugContainer.php","line":1084,"function":"create","class":"Symfony\\Component\\HttpClient\\HttpClient","type":"::"}],"count":1}}} []
[2021-10-14T12:50:01.653588+00:00] php.DEBUG: User Notice: Upgrade the curl extension or run "composer require amphp/http-client" to perform async HTTP operations, including full HTTP/2 support {"exception":{"Symfony\\Component\\ErrorHandler\\Exception\\SilencedErrorContext":{"severity":1024,"file":"C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\symfony\\http-client\\HttpClient.php","line":64,"trace":[{"file":"C:\\MAMP\\htdocs\\P6_01_projet\\var\\cache\\dev\\ContainerMZWWShC\\App_KernelDevDebugContainer.php","line":1084,"function":"create","class":"Symfony\\Component\\HttpClient\\HttpClient","type":"::"}],"count":1}}} []
[2021-10-14T12:50:01.740127+00:00] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\DriverException: "An exception occurred in driver: could not find driver" at C:\MAMP\htdocs\P6_01_projet\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\AbstractPostgreSQLDriver.php line 102 {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in driver: could not find driver at C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractPostgreSQLDriver.php:102)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDO\\Exception.php:18)\n[previous exception] [object] (PDOException(code: 0): could not find driver at C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOConnection.php:40)"} []
[2021-10-14T12:50:01.994084+00:00] request.CRITICAL: Exception thrown when handling an exception (Doctrine\DBAL\Exception\DriverException: An exception occurred in driver: could not find driver at C:\MAMP\htdocs\P6_01_projet\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\AbstractPostgreSQLDriver.php line 102) {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in driver: could not find driver at C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractPostgreSQLDriver.php:102)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDO\\Exception.php:18)\n[previous exception] [object] (PDOException(code: 0): could not find driver at C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOConnection.php:40)"} []
[2021-10-14T12:50:01.994524+00:00] php.CRITICAL: Uncaught Exception: An exception occurred in driver: could not find driver {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in driver: could not find driver at C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractPostgreSQLDriver.php:102)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDO\\Exception.php:18)\n[previous exception] [object] (PDOException(code: 0): could not find driver at C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOConnection.php:40)\n[previous exception] [object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in driver: could not find driver at C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractPostgreSQLDriver.php:102)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDO\\Exception.php:18)\n[previous exception] [object] (PDOException(code: 0): could not find driver at C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOConnection.php:40)"} []
[2021-10-14T12:50:01.996433+00:00] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\DriverException: "An exception occurred in driver: could not find driver" at C:\MAMP\htdocs\P6_01_projet\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\AbstractPostgreSQLDriver.php line 102 {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in driver: could not find driver at C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractPostgreSQLDriver.php:102)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDO\\Exception.php:18)\n[previous exception] [object] (PDOException(code: 0): could not find driver at C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOConnection.php:40)\n[previous exception] [object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in driver: could not find driver at C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractPostgreSQLDriver.php:102)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDO\\Exception.php:18)\n[previous exception] [object] (PDOException(code: 0): could not find driver at C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOConnection.php:40)"} []
[2021-10-14T12:50:02.511978+00:00] request.CRITICAL: Exception thrown when handling an exception (Doctrine\DBAL\Exception\DriverException: An exception occurred in driver: could not find driver at C:\MAMP\htdocs\P6_01_projet\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\AbstractPostgreSQLDriver.php line 102) {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in driver: could not find driver at C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractPostgreSQLDriver.php:102)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDO\\Exception.php:18)\n[previous exception] [object] (PDOException(code: 0): could not find driver at C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOConnection.php:40)"} []
[2021-10-14T12:50:02.512133+00:00] php.CRITICAL: Uncaught Exception: An exception occurred in driver: could not find driver {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in driver: could not find driver at C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractPostgreSQLDriver.php:102)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDO\\Exception.php:18)\n[previous exception] [object] (PDOException(code: 0): could not find driver at C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOConnection.php:40)\n[previous exception] [object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in driver: could not find driver at C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractPostgreSQLDriver.php:102)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDO\\Exception.php:18)\n[previous exception] [object] (PDOException(code: 0): could not find driver at C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOConnection.php:40)\n[previous exception] [object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in driver: could not find driver at C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractPostgreSQLDriver.php:102)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDO\\Exception.php:18)\n[previous exception] [object] (PDOException(code: 0): could not find driver at C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOConnection.php:40)"} []
[2021-10-14T12:54:56.288581+00:00] request.INFO: Matched route "app_home_homepage". {"route":"app_home_homepage","route_parameters":{"_route":"app_home_homepage","_controller":"App\\Controller\\homeController::homepage"},"request_uri":"http://127.0.0.1/P6_01_projet/public/","method":"GET"} []
[2021-10-14T12:54:56.300565+00:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":0} []
[2021-10-14T12:54:56.315800+00:00] php.DEBUG: User Warning: Configure the "curl.cainfo", "openssl.cafile" or "openssl.capath" php.ini setting to enable the CurlHttpClient {"exception":{"Symfony\\Component\\ErrorHandler\\Exception\\SilencedErrorContext":{"severity":512,"file":"C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\symfony\\http-client\\HttpClient.php","line":57,"trace":[{"file":"C:\\MAMP\\htdocs\\P6_01_projet\\var\\cache\\dev\\ContainerMZWWShC\\App_KernelDevDebugContainer.php","line":1084,"function":"create","class":"Symfony\\Component\\HttpClient\\HttpClient","type":"::"}],"count":1}}} []
[2021-10-14T12:54:56.315900+00:00] php.DEBUG: User Notice: Upgrade the curl extension or run "composer require amphp/http-client" to perform async HTTP operations, including full HTTP/2 support {"exception":{"Symfony\\Component\\ErrorHandler\\Exception\\SilencedErrorContext":{"severity":1024,"file":"C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\symfony\\http-client\\HttpClient.php","line":64,"trace":[{"file":"C:\\MAMP\\htdocs\\P6_01_projet\\var\\cache\\dev\\ContainerMZWWShC\\App_KernelDevDebugContainer.php","line":1084,"function":"create","class":"Symfony\\Component\\HttpClient\\HttpClient","type":"::"}],"count":1}}} []
[2021-10-14T12:54:56.422526+00:00] doctrine.DEBUG: SHOW FULL TABLES WHERE Table_type = 'BASE TABLE' [] []
[2021-10-14T12:54:56.426862+00:00] doctrine.DEBUG: SHOW FULL TABLES WHERE Table_type = 'BASE TABLE' [] []
[2021-10-14T12:54:56.427448+00:00] doctrine.DEBUG: SHOW FULL TABLES WHERE Table_type = 'BASE TABLE' [] []
[2021-10-14T13:43:05.280301+00:00] request.INFO: Matched route "app_home_homepage". {"route":"app_home_homepage","route_parameters":{"_route":"app_home_homepage","_controller":"App\\Controller\\homeController::homepage"},"request_uri":"http://127.0.0.1/P6_01_projet/public/","method":"GET"} []
[2021-10-14T13:43:05.284208+00:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":0} []
[2021-10-14T13:43:05.317359+00:00] php.DEBUG: User Warning: Configure the "curl.cainfo", "openssl.cafile" or "openssl.capath" php.ini setting to enable the CurlHttpClient {"exception":{"Symfony\\Component\\ErrorHandler\\Exception\\SilencedErrorContext":{"severity":512,"file":"C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\symfony\\http-client\\HttpClient.php","line":57,"trace":[{"file":"C:\\MAMP\\htdocs\\P6_01_projet\\var\\cache\\dev\\ContainerB78QGcV\\App_KernelDevDebugContainer.php","line":1085,"function":"create","class":"Symfony\\Component\\HttpClient\\HttpClient","type":"::"}],"count":1}}} []
[2021-10-14T13:43:05.317492+00:00] php.DEBUG: User Notice: Upgrade the curl extension or run "composer require amphp/http-client" to perform async HTTP operations, including full HTTP/2 support {"exception":{"Symfony\\Component\\ErrorHandler\\Exception\\SilencedErrorContext":{"severity":1024,"file":"C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\symfony\\http-client\\HttpClient.php","line":64,"trace":[{"file":"C:\\MAMP\\htdocs\\P6_01_projet\\var\\cache\\dev\\ContainerB78QGcV\\App_KernelDevDebugContainer.php","line":1085,"function":"create","class":"Symfony\\Component\\HttpClient\\HttpClient","type":"::"}],"count":1}}} []
[2021-10-14T13:43:05.355030+00:00] doctrine.DEBUG: SHOW FULL TABLES WHERE Table_type = 'BASE TABLE' [] []
[2021-10-14T13:43:05.359775+00:00] doctrine.DEBUG: SHOW FULL TABLES WHERE Table_type = 'BASE TABLE' [] []
[2021-10-14T13:43:05.360318+00:00] doctrine.DEBUG: SHOW FULL TABLES WHERE Table_type = 'BASE TABLE' [] []
[2021-10-14T14:20:17.703877+00:00] request.INFO: Matched route "app_home_homepage". {"route":"app_home_homepage","route_parameters":{"_route":"app_home_homepage","_controller":"App\\Controller\\homeController::homepage"},"request_uri":"http://127.0.0.1/P6_01_projet/public/","method":"GET"} []
[2021-10-14T14:20:17.713560+00:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":0} []
[2021-10-14T14:20:17.729131+00:00] php.DEBUG: User Warning: Configure the "curl.cainfo", "openssl.cafile" or "openssl.capath" php.ini setting to enable the CurlHttpClient {"exception":{"Symfony\\Component\\ErrorHandler\\Exception\\SilencedErrorContext":{"severity":512,"file":"C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\symfony\\http-client\\HttpClient.php","line":57,"trace":[{"file":"C:\\MAMP\\htdocs\\P6_01_projet\\var\\cache\\dev\\ContainerB78QGcV\\App_KernelDevDebugContainer.php","line":1085,"function":"create","class":"Symfony\\Component\\HttpClient\\HttpClient","type":"::"}],"count":1}}} []
[2021-10-14T14:20:17.729212+00:00] php.DEBUG: User Notice: Upgrade the curl extension or run "composer require amphp/http-client" to perform async HTTP operations, including full HTTP/2 support {"exception":{"Symfony\\Component\\ErrorHandler\\Exception\\SilencedErrorContext":{"severity":1024,"file":"C:\\MAMP\\htdocs\\P6_01_projet\\vendor\\symfony\\http-client\\HttpClient.php","line":64,"trace":[{"file":"C:\\MAMP\\htdocs\\P6_01_projet\\var\\cache\\dev\\ContainerB78QGcV\\App_KernelDevDebugContainer.php","line":1085,"function":"create","class":"Symfony\\Component\\HttpClient\\HttpClient","type":"::"}],"count":1}}} []
[2021-10-14T14:20:17.813576+00:00] doctrine.DEBUG: SHOW FULL TABLES WHERE Table_type = 'BASE TABLE' [] []
[2021-10-14T14:20:17.817302+00:00] doctrine.DEBUG: SHOW FULL TABLES WHERE Table_type = 'BASE TABLE' [] []
[2021-10-14T14:20:17.817696+00:00] doctrine.DEBUG: SHOW FULL TABLES WHERE Table_type = 'BASE TABLE' [] []
[2021-10-14T14:27:09.226138+00:00] request.INFO: Matched route "app_home_homepage". {"route":"app_home_homepage","route_parameters":{"_route":"app_home_homepage","_controller":"App\\Controller\\homeController::homepage"},"request_uri":"http://127.0.0.1/P6ElouanPeurou/P6ElouanPeurou/public/","method":"GET"} []
[2021-10-14T14:27:09.236426+00:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":0} []
[2021-10-14T14:27:09.252638+00:00] php.DEBUG: User Warning: Configure the "curl.cainfo", "openssl.cafile" or "openssl.capath" php.ini setting to enable the CurlHttpClient {"exception":{"Symfony\\Component\\ErrorHandler\\Exception\\SilencedErrorContext":{"severity":512,"file":"C:\\MAMP\\htdocs\\P6ElouanPeurou\\P6ElouanPeurou\\vendor\\symfony\\http-client\\HttpClient.php","line":57,"trace":[{"file":"C:\\MAMP\\htdocs\\P6ElouanPeurou\\P6ElouanPeurou\\var\\cache\\dev\\ContainerB78QGcV\\App_KernelDevDebugContainer.php","line":1085,"function":"create","class":"Symfony\\Component\\HttpClient\\HttpClient","type":"::"}],"count":1}}} []
[2021-10-14T14:27:09.252765+00:00] php.DEBUG: User Notice: Upgrade the curl extension or run "composer require amphp/http-client" to perform async HTTP operations, including full HTTP/2 support {"exception":{"Symfony\\Component\\ErrorHandler\\Exception\\SilencedErrorContext":{"severity":1024,"file":"C:\\MAMP\\htdocs\\P6ElouanPeurou\\P6ElouanPeurou\\vendor\\symfony\\http-client\\HttpClient.php","line":64,"trace":[{"file":"C:\\MAMP\\htdocs\\P6ElouanPeurou\\P6ElouanPeurou\\var\\cache\\dev\\ContainerB78QGcV\\App_KernelDevDebugContainer.php","line":1085,"function":"create","class":"Symfony\\Component\\HttpClient\\HttpClient","type":"::"}],"count":1}}} []
[2021-10-14T14:27:09.324317+00:00] doctrine.DEBUG: SHOW FULL TABLES WHERE Table_type = 'BASE TABLE' [] []
[2021-10-14T14:27:09.327999+00:00] doctrine.DEBUG: SHOW FULL TABLES WHERE Table_type = 'BASE TABLE' [] []
[2021-10-14T14:27:09.328374+00:00] doctrine.DEBUG: SHOW FULL TABLES WHERE Table_type = 'BASE TABLE' [] []
